# fakepay-provider Makefile

CAPABILITY_ID = "wasmcloud:examples:payments"
NAME = "fakepay-provider"
VENDOR = "wasmcloud"
PROJECT = fakepay_provider
VERSION = 0.1.1
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

